import type { QteDefinition } from "@/types/qte";

export const QTE_DEFINITIONS: QteDefinition[] = [
  // --- MASH ---
  {
    id: "qte-mash-quick-tap",
    type: "mash",
    role: "attacker",
    title: "Quick Tap",
    difficulty: 1,
    params: { target: 8, durationMs: 2000 },
  },
  {
    id: "qte-mash-power-strike",
    type: "mash",
    role: "attacker",
    title: "Power Strike",
    difficulty: 2,
    params: { target: 15, durationMs: 2000 },
  },
  {
    id: "qte-mash-rapid-jabs",
    type: "mash",
    role: "attacker",
    title: "Rapid Jabs",
    difficulty: 3,
    params: { target: 20, durationMs: 2500 },
  },
  {
    id: "qte-mash-fury-combo",
    type: "mash",
    role: "attacker",
    title: "Fury Combo",
    difficulty: 4,
    params: { target: 30, durationMs: 2000 },
  },
  {
    id: "qte-mash-overdrive",
    type: "mash",
    role: "attacker",
    title: "Overdrive",
    difficulty: 5,
    params: { target: 45, durationMs: 2000 },
  },

  // --- TRIVIA ---
  {
    id: "qte-trivia-planets",
    type: "trivia",
    role: "attacker",
    title: "Quick Fire",
    difficulty: 1,
    params: {
      question: "How many planets are in the Solar System?",
      options: ["7", "8", "9", "10"],
      correctIndex: 1,
      durationMs: 10_000,
    },
  },
  {
    id: "qte-trivia-water",
    type: "trivia",
    role: "defender",
    title: "Quick Fire",
    difficulty: 1,
    params: {
      question: "What is the chemical formula for water?",
      options: ["CO2", "H2O", "O2", "NaCl"],
      correctIndex: 1,
      durationMs: 10_000,
    },
  },
  {
    id: "qte-trivia-continents",
    type: "trivia",
    role: "attacker",
    title: "Geography",
    difficulty: 2,
    params: {
      question: "How many continents are there on Earth?",
      options: ["5", "6", "7", "8"],
      correctIndex: 2,
      durationMs: 8000,
    },
  },
  {
    id: "qte-trivia-light-speed",
    type: "trivia",
    role: "defender",
    title: "Science",
    difficulty: 2,
    params: {
      question: "Roughly how fast does light travel per second?",
      options: ["30 000 km", "300 000 km", "3 000 000 km", "30 km"],
      correctIndex: 1,
      durationMs: 8000,
    },
  },
  {
    id: "qte-trivia-shakespeare",
    type: "trivia",
    role: "attacker",
    title: "Literature",
    difficulty: 3,
    params: {
      question: "Who wrote 'Romeo and Juliet'?",
      options: ["Dickens", "Tolstoy", "Shakespeare", "Chaucer"],
      correctIndex: 2,
      durationMs: 7000,
    },
  },
  {
    id: "qte-trivia-nile",
    type: "trivia",
    role: "defender",
    title: "Geography",
    difficulty: 3,
    params: {
      question: "Which is the longest river in the world?",
      options: ["Amazon", "Yangtze", "Mississippi", "Nile"],
      correctIndex: 3,
      durationMs: 7000,
    },
  },
  {
    id: "qte-trivia-element-79",
    type: "trivia",
    role: "attacker",
    title: "Chemistry",
    difficulty: 4,
    params: {
      question: "What element has the atomic number 79?",
      options: ["Silver", "Platinum", "Gold", "Mercury"],
      correctIndex: 2,
      durationMs: 6000,
    },
  },
  {
    id: "qte-trivia-battle-of-hastings",
    type: "trivia",
    role: "defender",
    title: "History",
    difficulty: 4,
    params: {
      question: "In what year was the Battle of Hastings?",
      options: ["1066", "1088", "1044", "1099"],
      correctIndex: 0,
      durationMs: 6000,
    },
  },
  {
    id: "qte-trivia-mitochondria",
    type: "trivia",
    role: "attacker",
    title: "Biology",
    difficulty: 5,
    params: {
      question: "What is the powerhouse of the cell?",
      options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi body"],
      correctIndex: 2,
      durationMs: 5000,
    },
  },
  {
    id: "qte-trivia-mount-olympus",
    type: "trivia",
    role: "defender",
    title: "Mythology",
    difficulty: 5,
    params: {
      question: "How many Olympian gods are there in Greek mythology?",
      options: ["10", "12", "14", "9"],
      correctIndex: 1,
      durationMs: 5000,
    },
  },

  // --- SEQUENCE ---
  {
    id: "qte-sequence-dodge-step",
    type: "sequence",
    role: "defender",
    title: "Dodge Step",
    difficulty: 1,
    params: { sequence: ["↑", "→", "↓"], durationMs: 4000 },
  },
  {
    id: "qte-sequence-counter-step",
    type: "sequence",
    role: "defender",
    title: "Counter Step",
    difficulty: 3,
    params: { sequence: ["←", "↑", "→", "↑"], durationMs: 3000 },
  },
  {
    id: "qte-sequence-evasion-pattern",
    type: "sequence",
    role: "defender",
    title: "Evasion Pattern",
    difficulty: 4,
    params: { sequence: ["↑", "←", "↓", "→", "↑"], durationMs: 3000 },
  },
  {
    id: "qte-sequence-phantom-weave",
    type: "sequence",
    role: "defender",
    title: "Phantom Weave",
    difficulty: 5,
    params: { sequence: ["↓", "←", "↑", "→", "↓", "←"], durationMs: 2500 },
  },

  // --- TIMING ---
  {
    id: "qte-timing-strike-zone",
    type: "timing",
    role: "attacker",
    title: "Strike Zone",
    difficulty: 2,
    params: {
      zoneCenterPercent: 50,
      zoneWidthPercent: 40,
      cursorSpeedPercent: 60,
      durationMs: 4000,
    },
  },
  {
    id: "qte-timing-precision-hit",
    type: "timing",
    role: "attacker",
    title: "Precision Hit",
    difficulty: 3,
    params: {
      zoneCenterPercent: 50,
      zoneWidthPercent: 25,
      cursorSpeedPercent: 100,
      durationMs: 4000,
    },
  },
  {
    id: "qte-timing-critical-window",
    type: "timing",
    role: "attacker",
    title: "Critical Window",
    difficulty: 4,
    params: {
      zoneCenterPercent: 65,
      zoneWidthPercent: 12,
      cursorSpeedPercent: 160,
      durationMs: 4000,
    },
  },
  {
    id: "qte-timing-frame-perfect",
    type: "timing",
    role: "attacker",
    title: "Frame Perfect",
    difficulty: 5,
    params: {
      zoneCenterPercent: 72,
      zoneWidthPercent: 5,
      cursorSpeedPercent: 240,
      durationMs: 4000,
    },
  },

  // --- RECALL ---
  {
    id: "qte-recall-pattern-memory",
    type: "recall",
    role: "defender",
    title: "Pattern Memory",
    difficulty: 2,
    params: {
      sequence: ["↑", "→", "↓"],
      memorizeMs: 2500,
      inputDurationMs: 6000,
    },
  },
  {
    id: "qte-recall-battle-recall",
    type: "recall",
    role: "defender",
    title: "Battle Recall",
    difficulty: 3,
    params: {
      sequence: ["←", "↑", "→", "↓"],
      memorizeMs: 2000,
      inputDurationMs: 5000,
    },
  },
  {
    id: "qte-recall-flash-memory",
    type: "recall",
    role: "defender",
    title: "Flash Memory",
    difficulty: 4,
    params: {
      sequence: ["↓", "→", "↑", "←", "↓"],
      memorizeMs: 1500,
      inputDurationMs: 4000,
    },
  },
  {
    id: "qte-recall-instant-recall",
    type: "recall",
    role: "defender",
    title: "Instant Recall",
    difficulty: 5,
    params: {
      sequence: ["↑", "←", "↓", "→", "↑", "←"],
      memorizeMs: 1000,
      inputDurationMs: 3500,
    },
  },
];
