import type { QteDefinition } from "@/types/qte";

export const QTE_DEFINITIONS: QteDefinition[] = [
  // --- MASH ---
  {
    id: "qte-mash-quick-tap",
    type: "mash",
    role: "attacker",
    title: "Quick Tap",
    difficulty: 1,
    params: { target: 8, durationMs: 2000 },
  },
  {
    id: "qte-mash-power-strike",
    type: "mash",
    role: "attacker",
    title: "Power Strike",
    difficulty: 2,
    params: { target: 15, durationMs: 2000 },
  },
  {
    id: "qte-mash-rapid-jabs",
    type: "mash",
    role: "attacker",
    title: "Rapid Jabs",
    difficulty: 3,
    params: { target: 20, durationMs: 2500 },
  },
  {
    id: "qte-mash-fury-combo",
    type: "mash",
    role: "attacker",
    title: "Fury Combo",
    difficulty: 4,
    params: { target: 30, durationMs: 2000 },
  },
  {
    id: "qte-mash-overdrive",
    type: "mash",
    role: "attacker",
    title: "Overdrive",
    difficulty: 5,
    params: { target: 45, durationMs: 2000 },
  },

  // --- TRIVIA ---
  {
    id: "qte-trivia-html-tag",
    type: "trivia",
    role: "attacker",
    title: "HTML",
    difficulty: 1,
    params: {
      question: "Biggest heading tag?",
      options: ["<h6>", "<h1>", "<h3>", "<h0>"],
      correctIndex: 1,
      durationMs: 5000,
    },
  },
  {
    id: "qte-trivia-git-save",
    type: "trivia",
    role: "defender",
    title: "Git",
    difficulty: 1,
    params: {
      question: "Save staged changes?",
      options: ["git push", "git save", "git commit", "git merge"],
      correctIndex: 2,
      durationMs: 5000,
    },
  },
  {
    id: "qte-trivia-null-type",
    type: "trivia",
    role: "attacker",
    title: "JS",
    difficulty: 1,
    params: {
      question: "typeof null === ?",
      options: ["null", "undefined", "object", "boolean"],
      correctIndex: 2,
      durationMs: 5000,
    },
  },
  {
    id: "qte-trivia-array-filter",
    type: "trivia",
    role: "defender",
    title: "JS",
    difficulty: 1,
    params: {
      question: "Returns new filtered array?",
      options: ["forEach", "find", "filter", "reduce"],
      correctIndex: 2,
      durationMs: 5000,
    },
  },
  {
    id: "qte-trivia-http-ok",
    type: "trivia",
    role: "attacker",
    title: "HTTP",
    difficulty: 1,
    params: {
      question: "HTTP 'OK' status code?",
      options: ["201", "204", "301", "200"],
      correctIndex: 3,
      durationMs: 5000,
    },
  },
  {
    id: "qte-trivia-use-state",
    type: "trivia",
    role: "defender",
    title: "React",
    difficulty: 1,
    params: {
      question: "React hook for local state?",
      options: ["useEffect", "useRef", "useState", "useMemo"],
      correctIndex: 2,
      durationMs: 5000,
    },
  },
  {
    id: "qte-trivia-css-box-outer",
    type: "trivia",
    role: "attacker",
    title: "CSS",
    difficulty: 2,
    params: {
      question: "Outermost CSS box model layer?",
      options: ["padding", "border", "margin", "content"],
      correctIndex: 2,
      durationMs: 4000,
    },
  },
  {
    id: "qte-trivia-git-branch",
    type: "trivia",
    role: "defender",
    title: "Git",
    difficulty: 2,
    params: {
      question: "Create & switch branch?",
      options: ["git branch x", "git checkout -b x", "git switch x", "git new x"],
      correctIndex: 1,
      durationMs: 4000,
    },
  },
  {
    id: "qte-trivia-binary-search",
    type: "trivia",
    role: "attacker",
    title: "Algorithms",
    difficulty: 2,
    params: {
      question: "Binary search complexity?",
      options: ["O(n)", "O(n²)", "O(log n)", "O(1)"],
      correctIndex: 2,
      durationMs: 4000,
    },
  },
  {
    id: "qte-trivia-promise-then",
    type: "trivia",
    role: "defender",
    title: "JS",
    difficulty: 2,
    params: {
      question: "Promise resolved callback?",
      options: [".catch()", ".finally()", ".then()", ".done()"],
      correctIndex: 2,
      durationMs: 4000,
    },
  },
  {
    id: "qte-trivia-inner-join",
    type: "trivia",
    role: "attacker",
    title: "SQL",
    difficulty: 2,
    params: {
      question: "Only matching rows from both tables?",
      options: ["LEFT JOIN", "FULL JOIN", "CROSS JOIN", "INNER JOIN"],
      correctIndex: 3,
      durationMs: 4000,
    },
  },
  {
    id: "qte-trivia-solid-s",
    type: "trivia",
    role: "defender",
    title: "SOLID",
    difficulty: 2,
    params: {
      question: "'S' in SOLID?",
      options: ["Substitution", "Single Responsibility", "Separation", "Static"],
      correctIndex: 1,
      durationMs: 4000,
    },
  },
  {
    id: "qte-trivia-tcp-layer",
    type: "trivia",
    role: "attacker",
    title: "Networking",
    difficulty: 3,
    params: {
      question: "TCP operates on OSI layer?",
      options: ["3 Network", "4 Transport", "5 Session", "2 Data Link"],
      correctIndex: 1,
      durationMs: 3500,
    },
  },
  {
    id: "qte-trivia-closure",
    type: "trivia",
    role: "defender",
    title: "JS",
    difficulty: 3,
    params: {
      question: "Closure retains access to?",
      options: ["DOM nodes", "global scope", "outer scope", "call stack"],
      correctIndex: 2,
      durationMs: 3500,
    },
  },
  {
    id: "qte-trivia-hash-collision",
    type: "trivia",
    role: "attacker",
    title: "Data Structures",
    difficulty: 3,
    params: {
      question: "Hash collision means?",
      options: ["cache miss", "same bucket", "ring overflow", "table merge"],
      correctIndex: 1,
      durationMs: 3500,
    },
  },
  {
    id: "qte-trivia-event-loop",
    type: "trivia",
    role: "defender",
    title: "JS",
    difficulty: 3,
    params: {
      question: "Runs after call stack empties?",
      options: ["prototype chain", "task queue", "GC", "module loader"],
      correctIndex: 1,
      durationMs: 3500,
    },
  },
  {
    id: "qte-trivia-cap",
    type: "trivia",
    role: "attacker",
    title: "Systems",
    difficulty: 4,
    params: {
      question: "CAP = Consistency + Availability + ?",
      options: ["Performance", "Partition tolerance", "Persistence", "Parallelism"],
      correctIndex: 1,
      durationMs: 3000,
    },
  },
  {
    id: "qte-trivia-prototype-top",
    type: "trivia",
    role: "defender",
    title: "JS",
    difficulty: 4,
    params: {
      question: "Top of JS prototype chain?",
      options: ["Function.prototype", "Object.prototype", "null", "undefined"],
      correctIndex: 2,
      durationMs: 3000,
    },
  },
  {
    id: "qte-trivia-deadlock",
    type: "trivia",
    role: "attacker",
    title: "Concurrency",
    difficulty: 4,
    params: {
      question: "NOT needed for deadlock?",
      options: ["Mutual exclusion", "Hold & wait", "Starvation", "Circular wait"],
      correctIndex: 2,
      durationMs: 3000,
    },
  },
  {
    id: "qte-trivia-regex-lazy",
    type: "trivia",
    role: "defender",
    title: "Regex",
    difficulty: 4,
    params: {
      question: "Makes quantifier lazy?",
      options: ["+", "?", "*", "!"],
      correctIndex: 1,
      durationMs: 3000,
    },
  },
  {
    id: "qte-trivia-http-created",
    type: "trivia",
    role: "attacker",
    title: "HTTP",
    difficulty: 5,
    params: {
      question: "HTTP 'Created' code?",
      options: ["200", "204", "201", "202"],
      correctIndex: 2,
      durationMs: 2500,
    },
  },
  {
    id: "qte-trivia-git-rebase",
    type: "trivia",
    role: "defender",
    title: "Git",
    difficulty: 5,
    params: {
      question: "Rewrite commit history onto another branch?",
      options: ["git merge", "git cherry-pick", "git rebase", "git reset"],
      correctIndex: 2,
      durationMs: 2500,
    },
  },
  {
    id: "qte-trivia-immutable",
    type: "trivia",
    role: "attacker",
    title: "JS",
    difficulty: 5,
    params: {
      question: "Object.freeze makes object?",
      options: ["cloned", "sealed", "immutable", "private"],
      correctIndex: 2,
      durationMs: 2500,
    },
  },
  {
    id: "qte-trivia-css-specificity",
    type: "trivia",
    role: "defender",
    title: "CSS",
    difficulty: 5,
    params: {
      question: "Highest CSS specificity?",
      options: ["class", "element", "id", "inline style"],
      correctIndex: 3,
      durationMs: 2500,
    },
  },

  // --- SEQUENCE ---
  {
    id: "qte-sequence-dodge-step",
    type: "sequence",
    role: "defender",
    title: "Dodge Step",
    difficulty: 1,
    params: { sequence: ["↑", "→", "↓"], durationMs: 4000 },
  },
  {
    id: "qte-sequence-counter-step",
    type: "sequence",
    role: "defender",
    title: "Counter Step",
    difficulty: 3,
    params: { sequence: ["←", "↑", "→", "↑"], durationMs: 3000 },
  },
  {
    id: "qte-sequence-evasion-pattern",
    type: "sequence",
    role: "defender",
    title: "Evasion Pattern",
    difficulty: 4,
    params: { sequence: ["↑", "←", "↓", "→", "↑"], durationMs: 3000 },
  },
  {
    id: "qte-sequence-phantom-weave",
    type: "sequence",
    role: "defender",
    title: "Phantom Weave",
    difficulty: 5,
    params: { sequence: ["↓", "←", "↑", "→", "↓", "←"], durationMs: 2500 },
  },

  // --- TIMING ---
  {
    id: "qte-timing-strike-zone",
    type: "timing",
    role: "attacker",
    title: "Strike Zone",
    difficulty: 2,
    params: {
      zoneCenterPercent: 50,
      zoneWidthPercent: 40,
      cursorSpeedPercent: 60,
      durationMs: 4000,
    },
  },
  {
    id: "qte-timing-precision-hit",
    type: "timing",
    role: "attacker",
    title: "Precision Hit",
    difficulty: 3,
    params: {
      zoneCenterPercent: 50,
      zoneWidthPercent: 25,
      cursorSpeedPercent: 100,
      durationMs: 4000,
    },
  },
  {
    id: "qte-timing-critical-window",
    type: "timing",
    role: "attacker",
    title: "Critical Window",
    difficulty: 4,
    params: {
      zoneCenterPercent: 65,
      zoneWidthPercent: 12,
      cursorSpeedPercent: 160,
      durationMs: 4000,
    },
  },
  {
    id: "qte-timing-frame-perfect",
    type: "timing",
    role: "attacker",
    title: "Frame Perfect",
    difficulty: 5,
    params: {
      zoneCenterPercent: 72,
      zoneWidthPercent: 5,
      cursorSpeedPercent: 240,
      durationMs: 4000,
    },
  },

  // --- RECALL ---
  {
    id: "qte-recall-pattern-memory",
    type: "recall",
    role: "defender",
    title: "Pattern Memory",
    difficulty: 2,
    params: {
      sequence: ["↑", "→", "↓"],
      memorizeMs: 5000,
      inputDurationMs: 6000,
    },
  },
  {
    id: "qte-recall-battle-recall",
    type: "recall",
    role: "defender",
    title: "Battle Recall",
    difficulty: 3,
    params: {
      sequence: ["←", "↑", "→", "↓"],
      memorizeMs: 4500,
      inputDurationMs: 5000,
    },
  },
  {
    id: "qte-recall-flash-memory",
    type: "recall",
    role: "defender",
    title: "Flash Memory",
    difficulty: 4,
    params: {
      sequence: ["↓", "→", "↑", "←", "↓"],
      memorizeMs: 4000,
      inputDurationMs: 4000,
    },
  },
  {
    id: "qte-recall-instant-recall",
    type: "recall",
    role: "defender",
    title: "Instant Recall",
    difficulty: 5,
    params: {
      sequence: ["↑", "←", "↓", "→", "↑", "←"],
      memorizeMs: 3500,
      inputDurationMs: 3500,
    },
  },
];
